### ISSUE TITLE
Sip registration hijacking

### ISSUE THREAD

**Issue by hy0gy** [Pepelux/sippts#11]
Would be really really nice a tool which performs the sip registration hijacking ( deregistration + registration option and registration standalone option ), with all the customizations of the others one you already made

**Comment by Pepelux** [comment]
Could you send me an example? It works for me

**Comment by hy0gy** [comment]
Yeah, you are right, infact I removed the bug part, in the end the problem was not the tool(:
Just the suggestion has remained. I would like to help you  ( if you are interested ) in creating such tool, but I don't really know perl

**Comment by Pepelux** [comment]
It sounds great, but right now I don't have time to spend on the tool. Maybe later. However, feel free to program the script and I'll help you when I can.
