### ISSUE TITLE
CSeq: INVITE

### ISSUE THREAD

**Issue by samsomlw** [Pepelux/sippts#27]
why we have CSeq: 1 INVITE and CSeq: 2 INVITE
what is for request
Who will give me the correct response
some servers like cisco 
can invite just CSeq: 1  not need 2 
and some servers need 1 and need 2 

why i ass this . is that mean  
u need auth to create CSeq: 2 INVITE to call 
`if self.auth_user != '' and self.auth_pwd != '' and (headers['response_code'] == '401' or headers['response_code'] == '407'):`

but why `if  headers['response_code'] == '407')? `

**Comment by Pepelux** [comment]
----------
https://www.rfc-editor.org/rfc/rfc3261#section-20.16

The CSeq header field serves to order transactions
   within a dialog, to provide a means to uniquely identify
   transactions, and to differentiate between new requests and request
   retransmissions.
----------

The script starts with CSeq = 1 (although it could start with any other).

If the server requests authentication (code 401 Unauthorized or 407 Proxy Authentication Required) and we have provided the script with a valid user/pass, we increment the CSeq number for the second INVITE message (with digest auth)

**Comment by samsomlw** [comment]
Now I understand, thank you very much, my friend
and i need ask abut is invite script can call as uri 
and i need ask about sipdigestleak.py
this script result is 
`Auth=Digest username="pepelux", realm="asterisk", nonce="lcwnqoz0", uri="sip:100@192.168.2.235:56583;transport=UDP", response="31fece0d4ff6fd524c1d4c9482e99bb2", algorithm=MD5
`
this is digest for real password  so can i use it in my invire request

**Comment by Pepelux** [comment]
Digest is different for each authentication. You can't use a random data to authenticate. When a server offers a digest, nonce value changes for each request and the client generate a response using all data, like username, realm, nonce, algorithm, password, etc.

This attack (SIP Digest Leak) is to obtain all auth data of a digest authentication and next, try to crack the password with the script sipcrack.py, using brute force or a dictionary.
