### ISSUE TITLE
get response timeout

### ISSUE THREAD

**Issue by samsomlw** [Pepelux/sippts#28]
use this to add a timeout to while get response
            timeout = time.time() + int(defualtConnectionTimeout)
            while rescode[:1] == '1' and time.time() < timeout:

**Comment by Pepelux** [comment]
what script are you talking about?

**Comment by samsomlw** [comment]
like script invite when u  get response  if no connection to ip u will get infinty loop in while 
because you will always get the error 100 timeout

**Comment by Pepelux** [comment]
It doesn't work because the socket also waits for its timeout. I've solved it adding a try-except timeout and in case of socket timeout do an exit.

Thanks for the advise.
