### ISSUE TITLE
Wiki out of date

### ISSUE THREAD

**Issue by noraj** [Pepelux/sippts#3]
The examples on the wiki (ie. https://github.com/Pepelux/sippts/wiki/SIPScan) are for the 1.0. I updated the help message for 1.2 but the examples are still out of date using options that are no existing anymore like `-t`, etc.

**Comment by Pepelux** [comment]
-db param is a valid parameter. 
Changed -proto instead -t

Thanks

**Comment by noraj** [comment]
I was not saying that for me, I can read the help message but other people may be deceived by reading the wiki.
