### ISSUE TITLE
SIP/2.0 423 Interval Too Brief

### ISSUE THREAD

**Issue by sieteunoseis** [Pepelux/sippts#33]
When using sipcrack.py against a Cisco CUCM server I get a _SIP/2.0 423 Interval Too Brief_ back from the server. If you update _expires_ variable in the _create_message_ function from 60 to 120 it works. It would be nice to have this as an option.

`def create_message(method, ip_sdp, contactdomain, fromuser, fromname, fromdomain, touser, toname, todomain, proto, domain, useragent, fromport, branch, callid, tag, cseq, totag, digest, auth_type, referto, withsdp, via, rr, ppi, pai, header, withcontact):
    expires = '120'`

**Comment by Pepelux** [comment]
I have updated the expires header value to 120

Thanks
