### ISSUE TITLE
tool Working with TLS and UDP but no TCP 

### ISSUE THREAD

**Issue by lr2bmail** [Pepelux/sippts#34]
This tool is awesome when it comes to handling TLS and UDP, but I'm kinda stuck when it comes to TCP. I've been trying it out on my test IP, which I can scan with Nmap, but for some reason, this tool isn't giving me any results with TCP.
my ip has tls on and tcp 
```

3128/tcp closed squid-http
5060/tcp open   sip
5061/tcp open   sip-tls
```

**Comment by Pepelux** [comment]
If ports are open maybe they are filtering User-Agent pplsip. Have you tried with other UA? You can use param -ua

Cheers
