### ISSUE TITLE
I am having an error

### ISSUE THREAD

**Issue by X-n3t** [Pepelux/sippts#37]
┌──(root㉿MSI)-[/opt/sippts]
└─# source env/bin/activate

┌──(env)(root㉿MSI)-[/opt/sippts]
└─# pip install sippts
ERROR: Could not find a version that satisfies the requirement sippts (from versions: none)
ERROR: No matching distribution found for sippts

┌──(env)(root㉿MSI)-[/opt/sippts]
└─# pip install -r requirements.txt
Collecting netifaces (from -r requirements.txt (line 1))
  Using cached netifaces-0.11.0-cp311-cp311-linux_x86_64.whl
Collecting IPy (from -r requirements.txt (line 2))
  Using cached IPy-1.1-py3-none-any.whl
Collecting pyshark (from -r requirements.txt (line 3))
  Using cached pyshark-0.6-py3-none-any.whl (41 kB)
Collecting scapy (from -r requirements.txt (line 4))
  Using cached scapy-2.5.0-py2.py3-none-any.whl
Collecting ArpSpoof (from -r requirements.txt (line 5))
  Using cached ArpSpoof-1.1.2-py3-none-any.whl
Collecting websocket-client (from -r requirements.txt (line 6))
  Using cached websocket_client-1.6.4-py3-none-any.whl (57 kB)
Collecting rel (from -r requirements.txt (line 7))
  Using cached rel-0.4.9-py2.py3-none-any.whl (12 kB)
Collecting pyradamsa (from -r requirements.txt (line 8))
  Using cached pyradamsa-0.1.1-cp32-abi3-manylinux1_x86_64.whl (545 kB)
Collecting lxml (from pyshark->-r requirements.txt (line 3))
  Using cached lxml-4.9.3-cp311-cp311-manylinux_2_28_x86_64.whl (7.9 MB)
Collecting termcolor (from pyshark->-r requirements.txt (line 3))
  Using cached termcolor-2.3.0-py3-none-any.whl (6.9 kB)
Collecting packaging (from pyshark->-r requirements.txt (line 3))
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting appdirs (from pyshark->-r requirements.txt (line 3))
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting PythonToolsKit (from ArpSpoof->-r requirements.txt (line 5))
  Using cached PythonToolsKit-1.2.6-py3-none-any.whl
Installing collected packages: rel, pyradamsa, netifaces, IPy, appdirs, websocket-client, termcolor, scapy, PythonToolsKit, packaging, lxml, pyshark, ArpSpoof
Successfully installed ArpSpoof-1.1.2 IPy-1.1 PythonToolsKit-1.2.6 appdirs-1.4.4 lxml-4.9.3 netifaces-0.11.0 packaging-23.2 pyradamsa-0.1.1 pyshark-0.6 rel-0.4.9 scapy-2.5.0 termcolor-2.3.0 websocket-client-1.6.4

┌──(env)(root㉿MSI)-[/opt/sippts]
└─# python setup.py install
/opt/sippts/env/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
  warnings.warn(msg, _BetaConfiguration)
running install
/opt/sippts/env/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/sippts/env/lib/python3.11/site-packages/setuptools/command/easy_install.py:146: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing src/sippts.egg-info/PKG-INFO
writing dependency_links to src/sippts.egg-info/dependency_links.txt
writing requirements to src/sippts.egg-info/requires.txt
writing top-level names to src/sippts.egg-info/top_level.txt
reading manifest file 'src/sippts.egg-info/SOURCES.txt'
adding license file 'LICENSE.txt'
writing manifest file 'src/sippts.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipsniff.py -> build/bdist.linux-x86_64/egg/sippts
creating build/bdist.linux-x86_64/egg/sippts/lib
copying build/lib/sippts/lib/functions.py -> build/bdist.linux-x86_64/egg/sippts/lib
copying build/lib/sippts/lib/params.py -> build/bdist.linux-x86_64/egg/sippts/lib
copying build/lib/sippts/lib/functions_fuzz.py -> build/bdist.linux-x86_64/egg/sippts/lib
copying build/lib/sippts/lib/__init__.py -> build/bdist.linux-x86_64/egg/sippts/lib
copying build/lib/sippts/lib/logos.py -> build/bdist.linux-x86_64/egg/sippts/lib
copying build/lib/sippts/lib/color.py -> build/bdist.linux-x86_64/egg/sippts/lib
copying build/lib/sippts/sipflood.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipinvite.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/rtcpbleed.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipping.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/arpspoof.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipenumerate.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipcrack.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/siprcrack.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/wssend.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipsend.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/rtpbleedinject.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipexten.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipdigestleak.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipscan.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/siptshark.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/rtpbleedflood.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/rtpbleed.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipfuzzer.py -> build/bdist.linux-x86_64/egg/sippts
copying build/lib/sippts/sipdump.py -> build/bdist.linux-x86_64/egg/sippts
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipsniff.py to sipsniff.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/lib/functions.py to functions.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/lib/params.py to params.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/lib/functions_fuzz.py to functions_fuzz.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/lib/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/lib/logos.py to logos.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/lib/color.py to color.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipflood.py to sipflood.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipinvite.py to sipinvite.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/rtcpbleed.py to rtcpbleed.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipping.py to sipping.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/arpspoof.py to arpspoof.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipenumerate.py to sipenumerate.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipcrack.py to sipcrack.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/siprcrack.py to siprcrack.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/wssend.py to wssend.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipsend.py to sipsend.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/rtpbleedinject.py to rtpbleedinject.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipexten.py to sipexten.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipdigestleak.py to sipdigestleak.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipscan.py to sipscan.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/siptshark.py to siptshark.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/rtpbleedflood.py to rtpbleedflood.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/rtpbleed.py to rtpbleed.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipfuzzer.py to sipfuzzer.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/sippts/sipdump.py to sipdump.cpython-311.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/rtpbleedflood -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/rtpbleedinject -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipdigestleak -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipscan -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipsniff -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipping -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipinvite -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipflood -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipexten -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/rtcpbleed -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipdump -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/rtpbleed -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/arpspoof -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipsend -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/siptshark -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/wssend -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/siprcrack -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipfuzzer -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipcrack -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.11/sipenumerate -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/rtpbleedflood to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/rtpbleedinject to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipdigestleak to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipscan to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipsniff to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipping to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipinvite to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipflood to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipexten to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/rtcpbleed to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipdump to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/rtpbleed to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/arpspoof to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipsend to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/siptshark to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/wssend to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/siprcrack to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipfuzzer to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipcrack to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/sipenumerate to 755
copying src/sippts.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/sippts.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/sippts.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/sippts.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/sippts.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/sippts-3.4.dev0-py3.11.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing sippts-3.4.dev0-py3.11.egg
Copying sippts-3.4.dev0-py3.11.egg to /opt/sippts/env/lib/python3.11/site-packages
Adding sippts 3.4.dev0 to easy-install.pth file
Installing arpspoof script to /opt/sippts/env/bin
Installing rtcpbleed script to /opt/sippts/env/bin
Installing rtpbleed script to /opt/sippts/env/bin
Installing rtpbleedflood script to /opt/sippts/env/bin
Installing rtpbleedinject script to /opt/sippts/env/bin
Installing sipcrack script to /opt/sippts/env/bin
Installing sipdigestleak script to /opt/sippts/env/bin
Installing sipdump script to /opt/sippts/env/bin
Installing sipenumerate script to /opt/sippts/env/bin
Installing sipexten script to /opt/sippts/env/bin
Installing sipflood script to /opt/sippts/env/bin
Installing sipfuzzer script to /opt/sippts/env/bin
Installing sipinvite script to /opt/sippts/env/bin
Installing sipping script to /opt/sippts/env/bin
Installing siprcrack script to /opt/sippts/env/bin
Installing sipscan script to /opt/sippts/env/bin
Installing sipsend script to /opt/sippts/env/bin
Installing sipsniff script to /opt/sippts/env/bin
Installing siptshark script to /opt/sippts/env/bin
Installing wssend script to /opt/sippts/env/bin

Installed /opt/sippts/env/lib/python3.11/site-packages/sippts-3.4.dev0-py3.11.egg
Processing dependencies for sippts==3.4.dev0
Searching for websocket-client==1.6.4
Best match: websocket-client 1.6.4
Adding websocket-client 1.6.4 to easy-install.pth file
Installing wsdump script to /opt/sippts/env/bin

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for scapy==2.5.0
Best match: scapy 2.5.0
Adding scapy 2.5.0 to easy-install.pth file
Installing scapy script to /opt/sippts/env/bin

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for rel==0.4.9
Best match: rel 0.4.9
Adding rel 0.4.9 to easy-install.pth file
Installing rtimer script to /opt/sippts/env/bin

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for pyshark==0.6
Best match: pyshark 0.6
Adding pyshark 0.6 to easy-install.pth file

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for pyradamsa==0.1.1
Best match: pyradamsa 0.1.1
Adding pyradamsa 0.1.1 to easy-install.pth file

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for netifaces==0.11.0
Best match: netifaces 0.11.0
Adding netifaces 0.11.0 to easy-install.pth file

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for IPy==1.1
Best match: IPy 1.1
Adding IPy 1.1 to easy-install.pth file

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for ArpSpoof==1.1.2
Best match: ArpSpoof 1.1.2
Adding ArpSpoof 1.1.2 to easy-install.pth file
Installing ArpSpoof script to /opt/sippts/env/bin

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for appdirs==1.4.4
Best match: appdirs 1.4.4
Adding appdirs 1.4.4 to easy-install.pth file

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for packaging==23.2
Best match: packaging 23.2
Adding packaging 23.2 to easy-install.pth file

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for termcolor==2.3.0
Best match: termcolor 2.3.0
Adding termcolor 2.3.0 to easy-install.pth file

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for lxml==4.9.3
Best match: lxml 4.9.3
Adding lxml 4.9.3 to easy-install.pth file

Using /opt/sippts/env/lib/python3.11/site-packages
Searching for PythonToolsKit==1.2.6
Best match: PythonToolsKit 1.2.6
Adding PythonToolsKit 1.2.6 to easy-install.pth file
Installing Characters script to /opt/sippts/env/bin
Installing DebugEncoding script to /opt/sippts/env/bin

Using /opt/sippts/env/lib/python3.11/site-packages
Finished processing dependencies for sippts==3.4.dev0

┌──(env)(root㉿MSI)-[/opt/sippts]
└─# sipscan -h
Traceback (most recent call last):
  File "/opt/sippts/env/bin/sipscan", line 4, in <module>
    __import__('pkg_resources').run_script('sippts==3.4.dev0', 'sipscan')
  File "/opt/sippts/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 708, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/sippts/env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1528, in run_script
    exec(script_code, namespace, namespace)
  File "/opt/sippts/env/lib/python3.11/site-packages/sippts-3.4.dev0-py3.11.egg/EGG-INFO/scripts/sipscan", line 10, in <module>
ModuleNotFoundError: No module named 'sippts'

**Comment by X-n3t** [comment]
Script from wget https://github.com/Pepelux/sippts/archive/refs/tags/v3.3.zip works! :)
Gracias!

**Comment by linuxmaniac** [comment]
Works for me:
```
root@e57f96a286de:/# python3 -m venv /tmp/test
root@e57f96a286de:/# source /tmp/test/bin/activate
(test) root@e57f96a286de:/# cd /tmp
(test) root@e57f96a286de:/tmp/# git clone https://github.com/Pepelux/sippts.git
(test) root@e57f96a286de:/tmp# cd sippts/
(test) root@e57f96a286de:/tmp/sippts/# pip3 install -v -e .
[...]
Successfully installed ArpSpoof-1.1.2 IPy-1.1 PythonToolsKit-1.2.6 appdirs-1.4.4 lxml-4.9.3 netifaces-0.11.0 packaging-23.2 pyradamsa-0.1.1 pyshark-0.6 rel-0.4.9 scapy-2.5.0 sippts-3.4.dev0 termcolor-2.3.0 websocket-client-1.6.4
```

```
(test) root@e57f96a286de:/tmp/sippts# sipscan -h
usage: sipscan [-h] [-i IPADDR] [-proxy PROXY] [-r REMOTE_PORT] [-p PROTO] [-m METHOD] [-d DOMAIN] [-cd CONTACT_DOMAIN] [-fn FROM_NAME] [-fu FROM_USER] [-fd FROM_DOMAIN] [-tn TO_NAME] [-tu TO_USER] [-td TO_DOMAIN] [-ua USER_AGENT] [-th THREADS] [-ping] [-v] [-vv] [-f FILE] [-nocolor] [-o OFILE] [-fp] [-random]
               [-ppi PPI] [-pai PAI] [-local-ip LOCALIP]

☎  SIPPTS BY 🅿 🅴 🅿 🅴 🅻 🆄 🆇

█████████████████████████████████████████████
█─▄▄▄▄█▄─▄█▄─▄▄─███─▄▄▄▄█─▄▄▄─██▀▄─██▄─▀█▄─▄█
█▄▄▄▄─██─███─▄▄▄███▄▄▄▄─█─███▀██─▀─███─█▄▀─██
▀▄▄▄▄▄▀▄▄▄▀▄▄▄▀▀▀▀▀▄▄▄▄▄▀▄▄▄▄▄▀▄▄▀▄▄▀▄▄▄▀▀▄▄▀

💾 https://github.com/Pepelux/sippts
🐦 https://twitter.com/pepeluxx

 -= Fast SIP scanner =-

options:
  -h, --help                                      show this help message and exit
  -i IPADDR, --ip IPADDR                          Host/IP address/network (ex: mysipserver.com | 192.168.0.10 | 192.168.0.0/24)
  -proxy PROXY, --outbound_proxy PROXY            Use an outbound proxy (ex: 192.168.1.1 or 192.168.1.1:5070)
  -r REMOTE_PORT, --remote_port REMOTE_PORT       Ports to scan. Ex: 5060 | 5070,5080 | 5060-5080 | 5060,5062,5070-5080 | ALL for 1-65536 (default: 5060)
  -p PROTO, --proto PROTO                         Protocol: udp|tcp|tls|all (default: udp)
  -m METHOD, --method METHOD                      Method used to scan: options, invite, register (default: options)
  -d DOMAIN, --domain DOMAIN                      SIP Domain or IP address. Ex: my.sipserver.com (default: target IP address)
  -cd CONTACT_DOMAIN, --contact_domain CONTACT_DOMAIN
                                                  Domain or IP address for Contact header. Ex: 10.0.1.2
  -fn FROM_NAME, --from_name FROM_NAME            From Name. Ex: Bob
  -fu FROM_USER, --from_user FROM_USER            From User (default: 100)
  -fd FROM_DOMAIN, --from_domain FROM_DOMAIN      From Domain. Ex: 10.0.0.1
  -tn TO_NAME, --to_name TO_NAME                  To Name. Ex: Alice
  -tu TO_USER, --to_user TO_USER                  To User (default: 100)
  -td TO_DOMAIN, --to_domain TO_DOMAIN            To Domain. Ex: 10.0.0.1
  -ua USER_AGENT, --user_agent USER_AGENT         User-Agent header (default: pplsip)
  -th THREADS, --threads THREADS                  Number of threads (default: 200)
  -ping                                           Ping host before scan
  -v, --verbose                                   Increase verbosity
  -vv, --more_verbose                             Increase more verbosity
  -f FILE, --file FILE                            File with several IPs or network ranges
  -nocolor                                        Show result without colors
  -o OFILE, --output_file OFILE                   Save data into a log file
  -fp                                             Try to fingerprinting
  -random                                         Randomize target hosts
  -ppi PPI                                        P-Preferred-Identity
  -pai PAI                                        P-Asserted-Identity
  -local-ip LOCALIP                               Set local IP address (by default try to get it)


Fast SIP scanner using multithread. Sipscan can check several IPs and port ranges. It works with 
UDP, TCP and TLS protocols.
 
(test) root@e57f96a286de:/tmp/sippts# 
```
