### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by javiersopena** [Pepelux/sippts#38]
Hello. Just cloned the repo to test your tool, but it seems that python3 does not recognize the location for /lib functions.
I simply did
$ git clone https://github.com/Pepelux/sippts.git 
$ cd sippts 
$ pip3 install -r requirements.txt
$ cd src/sippts
$ python3 sipenumerate.py -h    
Traceback (most recent call last):
  File "/home/kali/milcom/sippts/src/sippts/sipenumerate.py", line 14, in <module>
    from .lib.functions import create_message, get_free_port, parse_message, fingerprinting, format_time
ImportError: attempted relative import with no known parent package

$ python3 sipfuzzer.py   
Traceback (most recent call last):
  File "/home/kali/milcom/sippts/src/sippts/sipfuzzer.py", line 20, in <module>
    from .lib.functions import create_message, get_free_port
ImportError: attempted relative import with no known parent package

**Comment by Pepelux** [comment]
You have to install it:

$ git clone https://github.com/Pepelux/sippts.git 
$ cd sippts 
$ pip3 install .

**Comment by javiersopena** [comment]
$ pip3 install .             
Defaulting to user installation because normal site-packages is not writeable
Processing /home/kali/milcom/sippts
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: netifaces in /usr/lib/python3/dist-packages (from sippts==3.4.dev0) (0.11.0)
Requirement already satisfied: IPy in /usr/lib/python3/dist-packages (from sippts==3.4.dev0) (1.1)
Requirement already satisfied: pyshark in /home/kali/.local/lib/python3.11/site-packages (from sippts==3.4.dev0) (0.6)
Requirement already satisfied: scapy in /usr/lib/python3/dist-packages (from sippts==3.4.dev0) (2.5.0)
Requirement already satisfied: ArpSpoof in /home/kali/.local/lib/python3.11/site-packages (from sippts==3.4.dev0) (1.1.2)
Requirement already satisfied: websocket-client in /usr/lib/python3/dist-packages (from sippts==3.4.dev0) (1.2.3)
Requirement already satisfied: rel in /home/kali/.local/lib/python3.11/site-packages (from sippts==3.4.dev0) (0.4.9.6)
Requirement already satisfied: pyradamsa in /home/kali/.local/lib/python3.11/site-packages (from sippts==3.4.dev0) (0.1.1)
Requirement already satisfied: PythonToolsKit in /home/kali/.local/lib/python3.11/site-packages (from ArpSpoof->sippts==3.4.dev0) (1.2.6)
Requirement already satisfied: lxml in /usr/lib/python3/dist-packages (from pyshark->sippts==3.4.dev0) (4.9.3)
Requirement already satisfied: termcolor in /usr/lib/python3/dist-packages (from pyshark->sippts==3.4.dev0) (1.1.0)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from pyshark->sippts==3.4.dev0) (23.1)
Requirement already satisfied: appdirs in /usr/lib/python3/dist-packages (from pyshark->sippts==3.4.dev0) (1.4.4)
Building wheels for collected packages: sippts
  Building wheel for sippts (pyproject.toml) ... done
  Created wheel for sippts: filename=sippts-3.4.dev0-py3-none-any.whl size=115542 sha256=5b0be1f3a571d9d4d0199608eebc50d9c264e36a77b3d4579ec074417beada22
  Stored in directory: /tmp/pip-ephem-wheel-cache-nv9euma_/wheels/e1/ef/62/2d159a06bec88fc8cf1cbcc49885f1322e60dd30df40b52a53
Successfully built sippts
Installing collected packages: sippts
Successfully installed sippts-3.4.dev0

$ cd src/sippts
$ python3 sipenumerate.py -h
Traceback (most recent call last):
  File "/home/kali/milcom/sippts/src/sippts/sipenumerate.py", line 14, in <module>
    from .lib.functions import create_message, get_free_port, parse_message, fingerprinting, format_time
ImportError: attempted relative import with no known parent package

**Comment by Pepelux** [comment]
no no no ... once installed it will be in the path. You can simple run:

$ sipenumerate -h

**Comment by javiersopena** [comment]
Aaaahm Thank you!

**Comment by javiersopena** [comment]
Solved!
