### ISSUE TITLE
Hard time packaging sippts

### ISSUE THREAD

**Issue by noraj** [Pepelux/sippts#4]
We have a hard time packaging sippts for BlackArch. See [#2336](https://github.com/BlackArch/blackarch/issues/2336).

The right packaging standard is to put the app data under `/usr/share/sippts/` and then create a wrapper in `/usr/bin/sipscan` to have the tool available. We packaged it [like this](https://github.com/BlackArch/blackarch/blob/master/packages/sippts/PKGBUILD) in the first place.

As you can see in [#2336](https://github.com/BlackArch/blackarch/issues/2336) the problem is that the script is looking for the database in the working directory. It would be cleaner and easier to package if sippts was using a configuration file (that could stay in `/usr/share/sippts/` or in ~/.config/sippts) where the database path is specified. Also `system("cp $database_empty $database") if (! -e $database);` should be removed so this would be done by the package that would copy the empty db to `~/.config/sippts` at installation (users that want to git clone and use the tool independently can still copy the db manually wherever they want).

**Comment by Pepelux** [comment]
Fixed

Commit: https://github.com/Pepelux/sippts/commit/128520e01f4bfc7ebfacbb5b1d55fa5280787a2c

**Comment by noraj** [comment]
@Pepelux Thanks, that was very quick.
