### ISSUE TITLE
Installation Error on Windows

### ISSUE THREAD

**Issue by skybeast235** [Pepelux/sippts#41]
$ git clone https://github.com/Pepelux/sippts.git
$ cd sippts
$ pip3 install .

After executing above commands i am still not able to execute sippts on windows below are screenshots please check

![image](https://github.com/Pepelux/sippts/assets/123854831/2b3717da-65f8-47fa-b3fd-718132a87c8c)

![image](https://github.com/Pepelux/sippts/assets/123854831/14a0f470-3058-469f-8b1b-2786bbb7ed90)

![image](https://github.com/Pepelux/sippts/assets/123854831/4ffd4db9-de27-4ad4-b88a-1895a7be6cdd)

![image](https://github.com/Pepelux/sippts/assets/123854831/1d072c51-7679-4cfc-92d3-06af93c4953d)

**Comment by Pepelux** [comment]
Sorry no support for Windows. I recommend you to use a Linux or Kali VM
