### ISSUE TITLE
AttributeError: 'RTPBleedInject' object has no attribute 'start_port'

### ISSUE THREAD

**Issue by jangpark** [Pepelux/sippts#42]
# sippts rtpbleedinject -i 192.168.1.1 -r 10070 -f audio.wav

☎️  SIPPTS BY 🅿 🅴 🅿 🅴 🅻 🆄 🆇

╔═╗╦╔═╗╔═╗╔╦╗╔═╗  ┬─┐┌┬┐┌─┐┌┐ ┬  ┌─┐┌─┐┌┬┐┬┌┐┌ ┬┌─┐┌─┐┌┬┐
╚═╗║╠═╝╠═╝ ║ ╚═╗  ├┬┘ │ ├─┘├┴┐│  ├┤ ├┤  ││││││ │├┤ │   │
╚═╝╩╩  ╩   ╩ ╚═╝  ┴└─ ┴ ┴  └─┘┴─┘└─┘└─┘─┴┘┴┘└┘└┘└─┘└─┘ ┴

💾 https://github.com/Pepelux/sippts
🐦 https://twitter.com/pepeluxx

[✓] Target IP: 192.168.1.1
Traceback (most recent call last):
  File "/usr/local/bin/sippts", line 717, in <module>
    main()
  File "/usr/local/bin/sippts", line 713, in main
    s.start()
  File "/usr/local/lib/python3.10/dist-packages/sippts/rtpbleedinject.py", line 36, in start
    f"{self.c.BWHITE}[✓] Port range: {self.c.YELLOW}{str(self.start_port)}{self.c.WHITE}-{self.c.YELLOW}{str(self.end_port)}"
AttributeError: 'RTPBleedInject' object has no attribute 'start_port'

I got this error, any solution?
thanks

**Comment by Pepelux** [comment]
Fixed  

Thanks for the report
