### ISSUE TITLE
407 Proxy Authentication Required

### ISSUE THREAD

**Issue by Yuki-XI** [Pepelux/sippts#43]
I'm Facing a problem while trying to do invite, i get 407 Proxy Authentication Required response.

BTW: I'm receiving the call with this error response but the script stopped direct 

[=>] Request INVITE from 123456789 to 987654321
[<=] Response from 123456789 to 987654321: 407 Proxy Authentication Required
[=>] Request ACK from 123456789 to 987654321
[=>] Request INVITE from 123456789 to 987654321
[<=] Response from 123456789 to 987654321: 407 Proxy Authentication Required
root@debian-armel:~/python/sippts/src#

**Comment by Pepelux** [comment]
This is not a issue. If the server requires authentication you can't call through it, if you don't know a valid user/pass. 

If you know it, you can add params -- user USERNAME --pass PASSWORD

**Comment by Yuki-XI** [comment]
The user and the password are added . and i'm able to make a call even with this error .
After searching I think there is something to do with Proxy-Authenticate and Proxy-Authorization .

**Comment by Pepelux** [comment]
I suppose you are talking about 'sippts invite' module. If you use user/pass, when it receive a 401 or 407 error, it sends digest authentication. If you receive the error again, it is because the user/pass are not correct.

Can you write here the command that you are using and the responses (with -v)? ... you can change the username, password and IP addresses with X's

**Comment by Pepelux** [comment]
I've just tried in a test server and it works fine:

➜  sippts git:(master) ✗ sippts invite -i XX.XX.XX.XX -r 5000 -user 200 -pass 1234

[✓] Target: XX.XX.XX.XX:5000/UDP
[✓] Total threads: 1
[✓] Call From: 200
[✓] Call To: 100

[=>] Request INVITE from 200 to 100
[<=] Response from 100 to 200: 401 Unauthorized
[=>] Request ACK from 200 to 100
[=>] Request INVITE from 200 to 100
[<=] Response from 100 to 200: 100 Trying
[<=] Response from 100 to 200: 200 OK
[=>] Request ACK from 200 to 100
